# Generated by Django 5.0.7 on 2024-08-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ('created_at',)},
        ),
    ]
